// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.Engine
{
    public partial class CalculatorUni
    {
        public global::Cysharp.Threading.Tasks.UniTask<int> AddAsync(int a, int b) => global::Cysharp.Threading.Tasks.UniTask.FromResult(a + b);
    }
}
