// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UnityAwaitable
{
    public partial class Calculator
    {
        public global::UnityEngine.Awaitable<int> AddAsync(int a, int b) => global::UnityEngine.Awaitable.FromResult(a + b);
    }
}
