// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public async global::GodotTask.GDTask<int> ComputeAsync()
        {
            var x = 1;
            var y = await global::GodotTask.GDTask.FromResult(2);
            return x + y;
        }
    }
}
