// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask DoAsync(System.Threading.CancellationToken ct)
        {
            return global::GodotTask.GDTask.CompletedTask;
        }
    }
}
