// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<T> WrapAsync<T>(T value)
            where T : class => global::GodotTask.GDTask.FromResult(value);
    }
}
