// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<T> CreateAsync<T>()
            where T : struct, new() => global::GodotTask.GDTask.FromResult(new T());
    }
}
