//HintName: Sample.Calculator.GDTask.g.cs
// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class Calculator
    {
        public global::GodotTask.GDTask DoNothingAsync() => throw new global::System.NotImplementedException();
        public global::GodotTask.GDTask<int> AddAsync(int a, int b) => throw new global::System.NotImplementedException();
    }
}
