//HintName: EngineTask.Attributes.g.cs
// <auto-generated/>
#nullable enable

namespace EngineTask
{
    internal enum TaskFlavour
    {
        GDTask,
        UniTask,
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class GenerateMirrorAttribute : global::System.Attribute
    {
        // Use a built-in flavour from the TaskFlavour enum.
        public GenerateMirrorAttribute(TaskFlavour flavour) { }

        // Use a custom flavour declared in an enginetask.json
        // AdditionalFile. See docs/extending.md.
        public GenerateMirrorAttribute(string flavourName) { }

        // Override the default mirror namespace (`{sourceNs}.GDTask` /
        // `{sourceNs}.UniTask` / `{sourceNs}.{CustomSuffix}`). Useful
        // when the surrounding solution already owns an
        // `MyLib.UniTask` namespace.
        public string? Namespace { get; set; }

        // Suffix appended to the mirror class's name — e.g.
        // [GenerateMirror(GDTask, ClassSuffix = "GD")] turns class
        // `WorkService` into mirror `WorkServiceGD` (still in the
        // mirror namespace).
        public string? ClassSuffix { get; set; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class MirrorIgnoreAttribute : global::System.Attribute
    {
    }
}
