//HintName: Sample.Calculator.GDTask.g.cs
// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class Calculator
    {
        public global::GodotTask.GDTask DoNothingAsync() => global::GodotTask.GDTask.CompletedTask;
        public global::GodotTask.GDTask<int> AddAsync(int a, int b) => global::GodotTask.GDTask.FromResult(a + b);
    }
}
