// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<int> SubAsync(int a, int b) => global::GodotTask.GDTask.FromResult(a - b);
    }
}

// === Diagnostics ===
// Warning: ENGTASK004: A method 'AddAsync' with this arity is already declared in a user-written partial of mirror class 'C'; the generated mirror will skip this method
