// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class Container
    {
        public partial class Inner
        {
            public global::GodotTask.GDTask<int> AddAsync(int a, int b) => global::GodotTask.GDTask.FromResult(a + b);
        }
    }
}
