// === Sample.Alpha.Inner.GDTask.g.cs ===
// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class Alpha
    {
        public partial class Inner
        {
            public global::GodotTask.GDTask<int> A() => global::GodotTask.GDTask.FromResult(1);
        }
    }
}

// === Sample.Beta.Inner.GDTask.g.cs ===
// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class Beta
    {
        public partial class Inner
        {
            public global::GodotTask.GDTask<int> B() => global::GodotTask.GDTask.FromResult(2);
        }
    }
}

