// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class Outer
    {
        public partial class Middle
        {
            public partial class Inner
            {
                public global::GodotTask.GDTask<int> AddAsync(int a, int b) => global::GodotTask.GDTask.FromResult(a + b);
            }
        }
    }
}
