// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask Good() => global::GodotTask.GDTask.CompletedTask;
    }
}

// === Diagnostics ===
// Error: ENGTASK003: Method 'BadAsync' is `async void`; mirrors require a task-like return type and the method will be skipped
