// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class NotPartial
    {
        public global::GodotTask.GDTask Done() => global::GodotTask.GDTask.CompletedTask;
    }
}

// === Diagnostics ===
// Warning: ENGTASK002: Class 'NotPartial' is not declared partial; mark it `partial` so consumers can extend the mirror with engine-specific code
