// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<int> Get(global::GodotTask.GDTask<int> t) => t;
    }
}
