// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask Cancel(System.Threading.CancellationToken ct) => global::GodotTask.GDTask.FromCanceled(ct);
    }
}
