// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<int> Make()
        {
            var tcs = new global::GodotTask.GDTaskCompletionSource<int>();
            return tcs.Task;
        }
    }
}
