// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask Fail(System.Exception ex) => global::GodotTask.GDTask.FromException(ex);
    }
}
