// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class C
    {
        public async global::GodotTask.GDTask DelayAsync() => await global::GodotTask.GDTask.Delay(100);
    }
}
