// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask AllOf(global::GodotTask.GDTask[] tasks) => global::GodotTask.GDTask.WhenAll(tasks);
    }
}
