// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<global::GodotTask.GDTask> AnyOf(global::GodotTask.GDTask[] tasks) => global::GodotTask.GDTask.WhenAny(tasks);
    }
}
