// <auto-generated/>
#nullable enable

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<int> Wrap(int v) => global::GodotTask.GDTask.FromResult(v);
    }
}
