// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask All(global::Cysharp.Threading.Tasks.UniTask a, global::Cysharp.Threading.Tasks.UniTask b) => global::Cysharp.Threading.Tasks.UniTask.WhenAll(a, b);
    }
}
