// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask<int> Done() => global::Cysharp.Threading.Tasks.UniTask.FromResult(42);
    }
}
