// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask Done() => global::Cysharp.Threading.Tasks.UniTask.CompletedTask;
    }
}
