// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask Bail(System.Threading.CancellationToken ct) => global::Cysharp.Threading.Tasks.UniTask.FromCanceled(ct);
    }
}
