// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask Wait() => global::Cysharp.Threading.Tasks.UniTask.Delay(1);
    }
}
