// <auto-generated/>
#nullable enable

using System.Collections.Generic;
using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask Consume(global::Cysharp.Threading.Tasks.IUniTaskAsyncEnumerable<int> source) => global::Cysharp.Threading.Tasks.UniTask.CompletedTask;
    }
}
