// === Sample.Calculator.GDTask.g.cs ===
// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class Calculator
    {
        public global::GodotTask.GDTask<int> AddAsync(int a, int b) => global::GodotTask.GDTask.FromResult(a + b);
    }
}

// === Sample.Calculator.UniTask.g.cs ===
// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class Calculator
    {
        public global::Cysharp.Threading.Tasks.UniTask<int> AddAsync(int a, int b) => global::Cysharp.Threading.Tasks.UniTask.FromResult(a + b);
    }
}

