// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask<global::Cysharp.Threading.Tasks.UniTask> Any(global::Cysharp.Threading.Tasks.UniTask a, global::Cysharp.Threading.Tasks.UniTask b) => global::Cysharp.Threading.Tasks.UniTask.WhenAny(a, b);
    }
}
