// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask Boom() => global::Cysharp.Threading.Tasks.UniTask.FromException(new System.Exception());
    }
}
