// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask<int> Boxed()
        {
            var tcs = new global::Cysharp.Threading.Tasks.UniTaskCompletionSource<int>();
            tcs.SetResult(42);
            return tcs.Task;
        }
    }
}
