// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask<int> Pass(global::Cysharp.Threading.Tasks.UniTask<int> t) => t;
    }
}
