// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.UniTask
{
    public partial class C
    {
        public global::Cysharp.Threading.Tasks.UniTask Pass(global::Cysharp.Threading.Tasks.UniTask t) => t;
    }
}
