// <auto-generated/>
#nullable enable

using System.Collections.Generic;
using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask Safe() => global::GodotTask.GDTask.CompletedTask;
    }
}

// === Diagnostics ===
// Warning: ENGTASK001: Method 'Consume' uses 'System.Collections.Generic.IAsyncEnumerable<int>', which has no translation for the target flavour; the mirror for this method will be skipped. Suppress with [MirrorIgnore] or extend the translation table.
