// <auto-generated/>
#nullable enable

using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask Safe() => global::GodotTask.GDTask.CompletedTask;
    }
}

// === Diagnostics ===
// Warning: ENGTASK001: Method 'Risky' uses 'System.Threading.Tasks.Task.Run<int>(System.Func<int>)', which has no translation for the target flavour; the mirror for this method will be skipped. Suppress with [MirrorIgnore] or extend the translation table.
