// <auto-generated/>
#nullable enable

using System;
using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask<Func<int>> Wrap(Func<int> f) => global::GodotTask.GDTask.FromResult(f);
    }
}
