// <auto-generated/>
#nullable enable

using System.Threading;
using EngineTask;

namespace Sample.GDTask
{
    public partial class C
    {
        public global::GodotTask.GDTask DoAsync(CancellationToken ct) => global::GodotTask.GDTask.CompletedTask;
    }
}
