namespace EngineTask.Generator;

internal static class AttributeSource
{
    public const string Text = """
        // <auto-generated/>
        #nullable enable

        namespace EngineTask
        {
            internal enum TaskFlavour
            {
                GDTask,
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateMirrorAttribute : global::System.Attribute
            {
                public GenerateMirrorAttribute(TaskFlavour flavour)
                {
                    Flavour = flavour;
                }

                public TaskFlavour Flavour { get; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            internal sealed class MirrorIgnoreAttribute : global::System.Attribute
            {
            }
        }

        """;
}
