using System.Text;

namespace EngineTask.Generator;

internal static class MirrorEmitter
{
    public static string Emit(MirrorTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(target.MirrorNamespace);
        sb.AppendLine("{");
        sb.Append("    public partial class ").AppendLine(target.ClassName);
        sb.AppendLine("    {");
        foreach (var method in target.Methods)
        {
            sb.Append("        ").AppendLine(method.Source.TrimEnd());
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
