using System.Text;

namespace EngineTask.Generator;

internal static class MirrorEmitter
{
    public static string Emit(MirrorTarget target)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append('\n');
        foreach (var u in target.Usings)
        {
            sb.Append(u).Append('\n');
        }
        if (target.Usings.Length > 0) sb.Append('\n');
        sb.Append("namespace ").Append(target.MirrorNamespace).Append('\n');
        sb.Append("{\n");
        sb.Append("    public partial class ").Append(target.MirrorClassName).Append('\n');
        sb.Append("    {\n");
        foreach (var method in target.Methods)
        {
            foreach (var line in method.Source.TrimEnd().Split('\n'))
            {
                sb.Append("        ").Append(line).Append('\n');
            }
        }
        sb.Append("    }\n");
        sb.Append("}\n");
        return sb.ToString();
    }
}
